export const personalInfo = {
  name: "Isahaq",
  title: "Senior Full Stack Developer",
  subtitle: "Full Stack Engineer",
  company: "Paragon Group",
  location: "Dhaka, Bangladesh",
  email: "hmisahaq01@gmail.com",
  github: "https://github.com/isahaq1",
  linkedin: "https://www.linkedin.com/in/hm-isahaq-6b1593132/",
  bio: "Senior Full Stack Developer with 6+ years of experience building enterprise-level applications. Passionate about clean architecture, microservices, and delivering scalable solutions that drive business impact.",
  shortBio:
    "Building next-generation web experiences with modern technologies, dynamic animations, intelligent interactions, and clean, high-performance design.",
  resumeUrl: "/resume",
};

export const skills = [
  {
    category: "Backend",
    icon: "⚙️",
    color: "#6366f1",
    items: [
      { name: "Laravel / PHP", level: 95 },
      { name: "Node.js / Express", level: 90 },
      { name: "Spring Boot", level: 72 },
      { name: "NestJS", level: 78 },
      { name: "RESTful APIs", level: 95 },
      { name: "Odoo ERP / Python", level: 80 },
      { name: "GraphQL", level: 70 },
    ],
  },
  {
    category: "Frontend",
    icon: "🎨",
    color: "#a855f7",
    items: [
      { name: "React.js", level: 88 },
      { name: "Next.js", level: 85 },
      { name: "TypeScript", level: 82 },
      { name: "Tailwind CSS", level: 90 },
      { name: "Vue / Nuxt.js", level: 70 },
    ],
  },
  {
    category: "Database",
    icon: "🗄️",
    color: "#06b6d4",
    items: [
      { name: "MySQL / PostgreSQL", level: 92 },
      { name: "MongoDB", level: 80 },
      { name: "Redis", level: 75 },
      { name: "Elasticsearch", level: 65 },
      { name: "Oracle / MSSQL", level: 70 },
    ],
  },
  {
    category: "DevOps & Cloud",
    icon: "☁️",
    color: "#10b981",
    items: [
      { name: "Docker / Kubernetes", level: 80 },
      { name: "Jenkins / CI-CD", level: 78 },
      { name: "AWS / Azure / GCP", level: 72 },
      { name: "Linux / Nginx", level: 85 },
      { name: "Kafka / RabbitMQ", level: 68 },
    ],
  },
];

// Flat list for the solar system orbit animation
export const skillPlanets = [
  { name: "Laravel", color: "#ef4444", size: 18, orbit: 1 },
  { name: "Node.js", color: "#22c55e", size: 16, orbit: 1 },
  { name: "React", color: "#3b82f6", size: 16, orbit: 1 },
  { name: "Next.js", color: "#f8fafc", size: 14, orbit: 1 },
  { name: "TypeScript", color: "#3178c6", size: 15, orbit: 2 },
  { name: "Docker", color: "#0ea5e9", size: 14, orbit: 2 },
  { name: "PostgreSQL", color: "#6366f1", size: 15, orbit: 2 },
  { name: "MySQL", color: "#f59e0b", size: 13, orbit: 2 },
  { name: "Redis", color: "#ef4444", size: 12, orbit: 3 },
  { name: "MongoDB", color: "#22c55e", size: 13, orbit: 3 },
  { name: "AWS", color: "#f97316", size: 12, orbit: 3 },
  { name: "Tailwind", color: "#06b6d4", size: 12, orbit: 3 },
  { name: "PHP", color: "#8b5cf6", size: 14, orbit: 2 },
  { name: "GraphQL", color: "#ec4899", size: 11, orbit: 3 },
  { name: "Jenkins", color: "#d946ef", size: 11, orbit: 3 },
  { name: "Linux", color: "#facc15", size: 13, orbit: 2 },
  { name: "NestJS", color: "#e11d48", size: 12, orbit: 3 },
  { name: "Kafka", color: "#a3a3a3", size: 11, orbit: 3 },
  { name: "K8s", color: "#3b82f6", size: 12, orbit: 3 },
  { name: "Vue", color: "#10b981", size: 12, orbit: 3 },
  { name: "Odoo", color: "#a24689", size: 14, orbit: 2 },
];

export const techStack = [
  "PHP",
  "Laravel",
  "Node.js",
  "React",
  "Next.js",
  "TypeScript",
  "Spring Boot",
  "NestJS",
  "Docker",
  "Kubernetes",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Tailwind CSS",
  "GraphQL",
  "Kafka",
  "Jenkins",
  "Linux",
  "Odoo",
  "Python",
];

export const experiences = [
  {
    id: 1,
    role: "Senior Full Stack Developer",
    company: "Paragon Group",
    period: "2026 – Present",
    type: "Current",
    description:
      "Leading full-stack development of enterprise solutions, architecting scalable microservices, and mentoring junior developers. Delivering high-impact digital transformation projects.",
    tech: ["Laravel", "Node.js", "React", "Next.js", "Odoo", "Docker", "MySQL"],
    highlights: [
      "Task & Ticketing System and Document Approval Application",
      "Canteen Management and Procurement applications",
      "Cattle Breeding and Poultry Breeding ERPs built on Odoo",
      "Architecting microservices-based enterprise solutions",
    ],
  },
  {
    id: 2,
    role: "Full Stack Developer",
    company: "Numatrix (SEBL | DX GROUP)",
    period: "2022 – 2026",
    type: "Previous",
    description:
      "Led cloud-based enterprise solution development using microservices architecture. Built and maintained multiple large-scale systems including ERP, HRMS, and Field Force Tracking applications.",
    tech: ["Node.js", "Next.js", "Laravel", "Jenkins", "Docker", "PostgreSQL"],
    highlights: [
      "EBS ERP System — microservices with Jenkins CI/CD pipeline",
      "HRMS — recruitment & barcode asset tracking for 500+ employees",
      "FFT Field Force Tracker — serving 550+ users with warranty management",
      "Financial Loan Module for IPDC — mobile API development",
    ],
  },
  {
    id: 3,
    role: "PHP Developer",
    company: "BDTask",
    period: "2019 – 2022",
    type: "Previous",
    description:
      "Developed large-scale web applications with a focus on performance optimization and CI/CD pipelines. Built ERP systems, pharmacy management, and HRMS platforms.",
    tech: [
      "PHP",
      "CodeIgniter",
      "Laravel",
      "MySQL",
      "Digital Ocean",
      "JavaScript",
    ],
    highlights: [
      "Full ERP System using PHP/CodeIgniter/MySQL on Digital Ocean",
      "Pharmacare — multi-branch pharmacy management system",
      "HRMS with fingerprint device integration",
      "Online bus ticketing & booking system",
    ],
  },
];

export const projects = [
  {
    id: 1,
    title: "EBS – Enterprise ERP System",
    description:
      "Cloud-based ERP built with microservices architecture. Handles inventory, finance, HR, and operations for a large enterprise. Deployed with Jenkins CI/CD on cloud infrastructure.",
    tech: ["Node.js", "Next.js", "PostgreSQL", "Docker", "Jenkins", "Redis"],
    category: "Enterprise",
    featured: true,
    link: null,
    github: null,
    color: "#6366f1",
  },
  {
    id: 2,
    title: "Barcode & QR Code Generator",
    description:
      "Open-source Composer package for Laravel and PHP. Supports 32+ barcode and QR formats including Code128, QR Code, PDF417, and more, with multiple output formats.",
    tech: ["PHP", "Laravel", "Composer", "Open Source"],
    category: "Open Source",
    featured: true,
    link: "https://packagist.org/packages/isahaq/barcode",
    github: "https://github.com/isahaq1/barcodeGeneratorPkg",
    color: "#a855f7",
    registry: "Composer",
    icon: "📦",
    install: "composer require isahaq/barcode",
    summary: "32+ barcode & QR formats for Laravel",
    stats: {
      formats: "32+",
      version: "v1.4.0",
      license: "MIT",
    },
  },
  {
    id: 7,
    title: "NumberToString — Multilingual Converter",
    description:
      "A powerful NPM package for converting numbers to words in 7+ languages including English, Bangla, French, Hindi, Spanish, Urdu, and Chinese. Supports currency formatting and large numbers up to billions.",
    tech: ["JavaScript", "Node.js", "NPM", "Open Source"],
    category: "Open Source",
    featured: true,
    link: "https://www.npmjs.com/package/@isahaq/numbertostring",
    github: "https://github.com/isahaq1/numbertostring",
    color: "#f59e0b",
    registry: "NPM",
    icon: "🌐",
    install: "npm i @isahaq/numbertostring",
    summary: "Numbers to words in 7+ languages",
    stats: {
      languages: "7+",
      version: "v2.8.0",
      license: "MIT",
    },
  },
  {
    id: 8,
    title: "Num2Str — Number to Words (EN / BN)",
    description:
      "Composer package for Laravel that converts numbers into English or Bangla words. Supports dependency injection, manual instantiation, and route closures. Compatible with PHP 8+ and Laravel 9 through 12.",
    tech: ["PHP", "Laravel", "Composer", "Open Source"],
    category: "Open Source",
    featured: true,
    link: "https://packagist.org/packages/isahaq/num2str",
    github: "https://github.com/isahaq1/num2wordConverter",
    color: "#ec4899",
    registry: "Composer",
    icon: "🔢",
    install: "composer require isahaq/num2str",
    summary: "Numbers to English & Bangla words",
    stats: {
      languages: "2",
      version: "v1.0.0",
      license: "MIT",
    },
  },
  {
    id: 9,
    title: "Modern CMS — Drag & Drop Website Builder",
    description:
      "Self-hosted, drag-and-drop website CMS built with Next.js, Express, and Prisma. Interactive installer scaffolds a full project with PostgreSQL or MySQL and S3, Azure Blob, or Cloudinary storage. Ships 30+ content blocks, draft/publish workflow, i18n with RTL, SEO, and RBAC.",
    tech: ["Next.js", "Express", "Prisma", "NPM", "Open Source"],
    category: "Open Source",
    featured: true,
    link: "https://www.npmjs.com/package/modern-cms",
    github: "https://github.com/isahaq1/Modern-CMS",
    color: "#22c55e",
    registry: "NPM",
    icon: "🧩",
    install: "npx modern-cms",
    summary: "Drag & drop CMS, scaffolded in one command",
    stats: {
      blocks: "30+",
      version: "v1.1.9",
      license: "MIT",
    },
  },
  {
    id: 3,
    title: "FFT – Field Force Tracker",
    description:
      "Real-time field force management system serving 550+ users. Features warranty management, asset tracking, and geolocation-based reporting for enterprise field operations.",
    tech: ["Laravel", "MySQL", "Redis", "REST API", "JavaScript"],
    category: "Enterprise",
    featured: true,
    link: null,
    github: null,
    color: "#06b6d4",
  },
  {
    id: 10,
    title: "Task & Ticketing System",
    description:
      "Internal task management and helpdesk ticketing platform with SLA tracking, priority queues, assignment workflows, escalation rules, and real-time status dashboards for support and operations teams.",
    tech: ["Laravel", "Next.js", "MySQL", "Redis", "REST API"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#8b5cf6",
  },
  {
    id: 11,
    title: "Document Approval Application",
    description:
      "Multi-level document approval workflow with configurable approval chains, digital sign-off, version history, audit trails, and notifications — replacing paper-based approvals across departments.",
    tech: ["Laravel", "React", "PostgreSQL", "Docker", "REST API"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#0ea5e9",
  },
  {
    id: 12,
    title: "Canteen Management System",
    description:
      "End-to-end canteen operations platform covering meal scheduling, employee subscriptions, token/QR-based serving, inventory, vendor billing, and consumption analytics.",
    tech: ["Laravel", "Node.js", "MySQL", "QR Code", "JavaScript"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#f97316",
  },
  {
    id: 13,
    title: "Procurement Application",
    description:
      "Procure-to-pay system with purchase requisitions, multi-stage approvals, vendor management, RFQ comparison, purchase orders, goods receipt, and budget controls integrated with finance.",
    tech: ["Laravel", "Next.js", "PostgreSQL", "Redis", "Docker"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#14b8a6",
  },
  {
    id: 14,
    title: "Cattle Breeding ERP (Odoo)",
    description:
      "Custom Odoo ERP for cattle breeding operations — herd registry, lineage and genetics tracking, breeding cycles, health and vaccination records, feed management, and farm-level financial reporting.",
    tech: ["Odoo", "Python", "PostgreSQL", "XML", "ERP"],
    category: "ERP",
    featured: false,
    link: null,
    github: null,
    color: "#84cc16",
  },
  {
    id: 15,
    title: "Poultry Breeding ERP (Odoo)",
    description:
      "Odoo-based ERP for poultry breeding — flock lifecycle management, hatchery and egg production tracking, feed conversion, mortality and biosecurity logs, and integrated sales and inventory.",
    tech: ["Odoo", "Python", "PostgreSQL", "XML", "ERP"],
    category: "ERP",
    featured: false,
    link: null,
    github: null,
    color: "#eab308",
  },
  {
    id: 4,
    title: "HRMS with Biometric Integration",
    description:
      "Complete HR management system with fingerprint device integration for attendance, payroll automation, leave management, and recruitment tracking.",
    tech: ["Laravel", "PHP", "MySQL", "JavaScript", "Biometric SDK"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#10b981",
  },
  {
    id: 5,
    title: "CI/CD Pipeline Infrastructure",
    description:
      "Full DevOps pipeline setup using Docker, Kubernetes, and Jenkins for automated testing, building, and deployment across multiple environments.",
    tech: ["Docker", "Kubernetes", "Jenkins", "Linux", "Shell Script"],
    category: "DevOps",
    featured: false,
    link: null,
    github: "https://github.com/isahaq1",
    color: "#f59e0b",
  },
  {
    id: 6,
    title: "Pharmacare Management System",
    description:
      "Multi-branch pharmacy management system with inventory control, sales tracking, prescription management, and financial reporting across multiple locations.",
    tech: ["PHP", "CodeIgniter", "MySQL", "Bootstrap", "jQuery"],
    category: "Enterprise",
    featured: false,
    link: null,
    github: null,
    color: "#ef4444",
  },
];

export const stats = [
  { label: "Years Experience", value: "6+", suffix: "" },
  { label: "Projects Delivered", value: "30+", suffix: "" },
  { label: "Technologies", value: "20+", suffix: "" },
  { label: "Users Served", value: "1K+", suffix: "" },
];

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Experience", href: "#experience" },
  { label: "Projects", href: "#projects" },
  { label: "Contact", href: "#contact" },
];
